USE [master]
GO

/****** Object:  Database [e11]    Script Date: 21/01/2021 22:24:41 ******/
CREATE DATABASE [e11]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'e11', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\e11.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'e11_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\e11_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [e11].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [e11] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [e11] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [e11] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [e11] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [e11] SET ARITHABORT OFF 
GO

ALTER DATABASE [e11] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [e11] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [e11] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [e11] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [e11] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [e11] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [e11] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [e11] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [e11] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [e11] SET  DISABLE_BROKER 
GO

ALTER DATABASE [e11] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [e11] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [e11] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [e11] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [e11] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [e11] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [e11] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [e11] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [e11] SET  MULTI_USER 
GO

ALTER DATABASE [e11] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [e11] SET DB_CHAINING OFF 
GO

ALTER DATABASE [e11] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [e11] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [e11] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [e11] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [e11] SET QUERY_STORE = OFF
GO

ALTER DATABASE [e11] SET  READ_WRITE 
GO

